[package]
name = "version_it"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
chrono = "0.4.40"
clap = {version = "4.5.37", features = ["derive"]}
colored = "3.0.0"
flate2 = "1.1.1"
hex = "0.4.3"
sha2 = "0.10.8"
ignore = "0.4"
